nameOverride: ""
fullnameOverride: ""

replicaCount: 1

command: ""
rootDir: ""

image:
  repository:
  tag: latest
  pullPolicy: IfNotPresent

storage:
  # GCP provisioner
  provisioner: kubernetes.io/gce-pd
  # Standard (non-SSD) disk
  type: pd-standard
  # Regional Disk
  replicationType: regional-pd
  # Replication zones
  zones: us-west1-a, us-west1-b
  # Disk size
  size: 2Gi

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
