apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cosmos.fullname" . }}-configmap
  labels:
    app.kubernetes.io/name: {{ include "cosmos.name" . }}
    helm.sh/chart: {{ include "cosmos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{ (tpl (.Files.Glob "config/*").AsConfig .) | indent 2 }}
