apiVersion: v1
kind: Service
metadata:
  name: {{ include "cosmos.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "cosmos.name" . }}
    helm.sh/chart: {{ include "cosmos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: LoadBalancer
  ports:
    - port: 26656
      targetPort: 26656
      protocol: TCP
      name: peer
  selector:
    app.kubernetes.io/name: {{ include "cosmos.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
